sudo: required
services:
  - docker

before_install:
  - docker build -t amirrezafahimi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amirrezafahimi/docker-react npm run test